### ISSUE TITLE
Determine which CI provider to use

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#9]
**Description of Problem**

See [this comment in #6](https://github.com/JordanMartinez/purescript-cookbook/pull/6#discussion_r438515055) for more context. We're currently using GitHub CI. I'm not sure I want to continue using that because of being less familiar with that. However, I also don't want to use Travis because "everyone does that."

I'd like to discuss this further as to which one we should use and why.

**Comment by milesfrain** [comment]
No qualms with giving travis another shot. This is the `.travis.yml` that I was attempting to use earlier:
```yml
dist: bionic
language: node_js
node_js: 12
install:
  - npm install
script:
  - npm run build
```

**Comment by JordanMartinez** [comment]
[Based on the file I use for my learning reference](https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/.travis.yml), maybe this would suffice?
```yml
dist: bionic
language: minimal
  # Use `nvm` to install latest version of NodeJS

# Unless we specify "sudo: false", build runs in VM, not container

# Limit the number of commits it will clone
git:
  depth: 3

# Only do CI for the default branch
branches:
  only:
  - master

before_install:
  - nvm install node
  - npm i -g npm

install:
  - npm i

script:
  - npm run build

cache:
  directories:
    - .spago
    - node_modules
```
